//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shows_Downloaded.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=\"|DataDirectory|\\Shows To Download.m" +
            "db\"")]
        public string Shows_To_DownloadConnectionString {
            get {
                return ((string)(this["Shows_To_DownloadConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=192.168.1.100;user id=Shane;password=kodiak;persistsecurityinfo=True;datab" +
            "ase=showstodownload")]
        public string showstodownloadConnectionString {
            get {
                return ((string)(this["showstodownloadConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowOnHiatus {
            get {
                return ((bool)(this["ShowOnHiatus"]));
            }
            set {
                this["ShowOnHiatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCancelled {
            get {
                return ((bool)(this["ShowCancelled"]));
            }
            set {
                this["ShowCancelled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30;200;100;75;100;100;100;100;100")]
        public string ListColumnSizes {
            get {
                return ((string)(this["ListColumnSizes"]));
            }
            set {
                this["ListColumnSizes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSkippedWeek {
            get {
                return ((bool)(this["ShowSkippedWeek"]));
            }
            set {
                this["ShowSkippedWeek"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SpringGreen")]
        public global::System.Drawing.Color ColorDownloaded {
            get {
                return ((global::System.Drawing.Color)(this["ColorDownloaded"]));
            }
            set {
                this["ColorDownloaded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color ColorSkipped {
            get {
                return ((global::System.Drawing.Color)(this["ColorSkipped"]));
            }
            set {
                this["ColorSkipped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tomato")]
        public global::System.Drawing.Color ColorNotDownloaded {
            get {
                return ((global::System.Drawing.Color)(this["ColorNotDownloaded"]));
            }
            set {
                this["ColorNotDownloaded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HotPink")]
        public global::System.Drawing.Color ColorMissedWeek {
            get {
                return ((global::System.Drawing.Color)(this["ColorMissedWeek"]));
            }
            set {
                this["ColorMissedWeek"] = value;
            }
        }
    }
}
